{% set name = "odc-loader" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/odc_loader-{{ version }}.tar.gz
  sha256: 90cada438cb7ac26db3c3b87b9ca72d9047a1e53ceb9e1df0a80859cf1ae71ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - odc-geo >=0.4.7
    - rasterio >=1.0.0,!=1.3.0,!=1.3.1
    - dask-core
    - numpy >=1.20.0
    - pandas
    - toolz
    - xarray >=0.19
    - zarr >=2.18.3,<3

test:
  imports:
    - odc.loader
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opendatacube/odc-loader/
  summary: Tooling for constructing xarray objects from parsed metadata
  license: 'Apache-2.0'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - omad
    - SpacemanPaul
    - Kirill888
    - Ariana-B
